### ISSUE TITLE
Client not starting up

### ISSUE THREAD

**Issue by shdblowers** [rootsdev/familysearch-reference-client#11]
Hello I have followed these steps:

```
 3260  git clone git@github.com:rootsdev/familysearch-reference-client.git
 3261  cd familysearch-reference-client
 3262  npm install
 3263  npm install -g bower
 3264  npm install -g grunt-cli
 3265  atom .
 3266  bower install
 3267  grunt watch
 3268  npm install
 3269  grunt watch
 3270  bower install
 3271  npm install grunt-parallel
 3272  grunt watch
 3273  grunt watch --force
 3274  npm install
 3275  sudo rm -rf node_modules
 3276  grunt watch
 3277  grunt watch --forace
 3278  grunt watch --force
 3279  npm install
 3280  grunt watch --force
 3281  sudo rm -rf node_modules
 3282  npm install
 3283  grunt watch
 3284  grunt watch --force
 3285  npm upgrade karma
 3286  npm install karma --save-dev
 3287  grunt watch --force
```

I also installed PhantomJS and put my app key in `src/app/app.js`.

This is the output I get:

```
Running "delta" task
Waiting...
/home/steven/work/familysearch-reference-client/node_modules/karma/lib/logger.js:59
  if (helper.isDefined(config.colors)) {
                             ^

TypeError: Cannot read property 'colors' of null
    at Object.setupFromConfig (/home/steven/work/familysearch-reference-client/node_modules/karma/lib/logger.js:59:30)
    at new Server (/home/steven/work/familysearch-reference-client/node_modules/karma/lib/server.js:50:10)
    at ReadStream.<anonymous> (/home/steven/work/familysearch-reference-client/node_modules/grunt-karma/lib/background.js:4:16)
    at emitNone (events.js:105:13)
    at ReadStream.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:516:10)
    at emitReadable (_stream_readable.js:510:7)
    at ReadStream.Readable.read (_stream_readable.js:387:7)
    at ReadStream.Socket.read (net.js:363:43)
    at nReadingNextTick (_stream_readable.js:800:8)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:611:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

```

**Comment by shdblowers** [comment]
Please let me know if you need more information.

**Comment by DallanQ** [comment]
I am pretty sure the familysearch reference client has been deprecated, but I'll let familysearch people say definitively.

Is anyone using it?

**Comment by shdblowers** [comment]
Not here, we were just trying to get it to run locally

**Comment by DallanQ** [comment]
This reference client is based upon the original (non-lite) version of the javascript client, which I heard was deprecated because it was too difficult for FamilySearch to keep up to date as they made changes to their API. I'm not sure how much work it would take to get this client to work at this point.
